---
name: cmpsc-100-course-project-docs
break: true
indent: 4
---

0_concept_statement.md:
    ConfirmFileExists
    CountFileWords --count 100

1_progress_report.md:
    ConfirmFileExists
    CountMarkdownTags --tag "list" --count 1
    CountFileWords --count 300

2_final_report.md:
    ConfirmFileExists
    CountFileWords --count 500